### PR TITLE
Idrinth

### PR DESCRIPTION
**Pull request by Idrinth**
changes to reduce the chances of stuff bugging out

### CODE REVIEW

**Review by w20k — COMMENTED** [review]
Seems good!

**Comment by w20k** [comment]
Update branch and merge ;)

**Comment by Idrinth** [comment]
will officially need a new codereview, if possible this time one that works :P have a look at https://github.com/Idrinth/IDotD/wiki/Developer-Information#commits - will happily add more if desired

**Comment by w20k** [comment]
Hmm...works a bit strange :)  Can't approve after I've added a comment. Odd.

**Comment by Idrinth** [comment]
LGTM just checks the comments, so just writing one here starting with any of the options should work :)

was still the easiest option, but if you find one better working, we can switch :)

**Comment by w20k** [comment]
Approved 👍

**Pull request merged**
