### PR TITLE
Idrinth

### PR DESCRIPTION
**Pull request by Idrinth**

### CODE REVIEW

**Comment by Idrinth** [comment]
@w20k would love some feedback about the structure there atm - still not sure if that grouping makes sense.

**Comment by w20k** [comment]
LGTM

**Comment by w20k** [comment]
Good thing, that you've started using docs, nice @Idrinth ;)

Though I would consider to overlook this part -> 

```
 idrinth.core.ajax.runHome ( '', function ( file ) {
            var applyRecursive = function ( to, from, func ) {
                for (var prop in from) {
                    if ( from.hasOwnProperty ( prop ) ) {
                        if ( typeof to[prop] === 'string' && typeof from[prop] === 'string' ) {
                            to[prop] = file[prop];
                        } else if ( typeof to[prop] === 'object' && typeof from[prop] === 'object' ) {
                            func ( to[prop], from[prop], func );
                        }
                    }
                }
            };
            applyRecursive ( idrinth.text.data, JSON.parse ( file ), applyRecursive );
        }, idrinth.text.start, idrinth.text.start, null, true );
```

**Review by w20k — APPROVED** [review]

**Review by w20k — APPROVED** [review]

**Comment by w20k** [comment]
LGTM

**Pull request merged**
