### PR TITLE
Fixes #251 

### LINKED ISSUE #251: Add missing replacements for translations
see https://github.com/IDotD/Translations/issues/2#issuecomment-272223233

### PR DESCRIPTION
**Pull request by Ardenian**
Fixes #251 
I was unable to locate http://image.prntscr.com/image/0c252f1fd29d41ffa479e5b3a27bcfc4.png from https://github.com/IDotD/Userscript/issues/251#issuecomment-272422262
Only found https://github.com/IDotD/Userscript/blob/master/src/mods/ui.js#L1017 but that value seems to be doing something else.
This Pull Request was successfully tested with de.json, though it does that at the moment:
fixme
No clue why, maybe it needs some time to update my branch with my latest commits.

### CODE REVIEW

**Comment by Idrinth** [comment]
https://github.com/IDotD/Userscript/blob/master/src/mods/ui.js#L1017 is for the settings window, https://github.com/IDotD/Userscript/blob/master/src/mods/tier.js#L78 is the one you#re looking for

**Comment by Ardenian** [comment]
Thank you, added it. The only thing missing now are the foldout names.

**Comment by Idrinth** [comment]
are you looking for https://github.com/IDotD/Userscript/blob/master/src/mods/ui.js#L921 by chance?

**Comment by Ardenian** [comment]
No, thank you, that one is already covered with https://github.com/IDotD/Userscript/pull/259/commits/13d3c07d6c2d689430b19afd87f28714e4e31794

I refer to these ones: 
foldout

EDIT: Found them

**Comment by Idrinth** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/IDotD/Userscript/pull-request/259/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=IDotD/Userscript)

**Pull request merged**
