### PR TITLE
Idrinth

### PR DESCRIPTION
**Pull request by Idrinth**
mostly bugfixing:
- wrong texts
- missing check for variable type
- removing clipboard.js

### CODE REVIEW

**Comment by w20k** [comment]
Looks great, thanks for backing me up :) Just finishing all my stuff for a weekends, to get myself into code ;) 
Write down, when you're finish with commits :)

**Comment by Idrinth** [comment]
done with commits, just give codacy a moment - just in case I messed up something

**Comment by w20k** [comment]
LGTM

**Review by w20k — APPROVED** [review]

**Comment by w20k** [comment]
Done :)

**Pull request merged**
