### PR TITLE
Idrinth

### PR DESCRIPTION
**Pull request by Idrinth**
mostly fixes, but also some reworking of the settings

### CODE REVIEW

**Comment by Idrinth** [comment]
should have been #176 instead of #76, will close and reopen accordingly once merged in

**Comment by w20k** [comment]
Actually, you could change comment message, if you want :) Thought a bit pain in arsch :D

Will take a look, after shopping is done!

**Comment by Idrinth** [comment]
the effort for that is just a bit too high imo :D easier to just reopen/close manually

**Review by w20k — APPROVED** [review]

**Comment by w20k** [comment]
LGTM

**Pull request merged**
