### PR TITLE
Theodotos

### PR DESCRIPTION
**Pull request by Theodotosp**

### CODE REVIEW

**Review by Idrinth — CHANGES_REQUESTED** [review]
The formatting looks off, for example line 9 of Bloodsuckers has the } too far to the left, it should be at the same position as the first character of "100000000".

This would likely prevent misscounting braces ;)

**Review by Idrinth — APPROVED** [review]

**Comment by Idrinth** [comment]
LGTM
just did the reformatting for you, @Theodotosp

**Comment by Theodotosp** [comment]
ok, i did this kind of formatting so that i can check if i have all the branches opened and closed correctly. Didnt figure this could create a problem,sorry.

**Comment by Idrinth** [comment]
there is no technical issue, it was just far away from the standard we had set for the project. I hope this is still easily readable for you, @Theodotosp ?

**Comment by Theodotosp** [comment]
of course it is easily readable :)

**Pull request merged**
