### PR TITLE
preparation multiple tickets

### PR DESCRIPTION
**Pull request by Idrinth**
Refs #91 changes the url to a proper one
Refs #108, Refs #66 provides a mechanism to bind events to css-classes

### CODE REVIEW

**Comment by w20k** [comment]
Are sure okey to use funciton that might not be compatible with every browser or we support only latest? :)
PS: Could be good idea to add device support table to README.

**Comment by Idrinth** [comment]
there's a small polyfill to solve that issue, but I agree, we should add the supported browsers to the readme.

**Review by w20k — APPROVED** [review]

**Comment by Idrinth** [comment]
ok, LGTM seems to be somewhat broken - 1 appproval required 1 given :/

**Comment by Idrinth** [comment]
ok, my mistake: github approvals !== lgtm approvals
LGTM needs a comment written and can be better configured - https://github.com/Idrinth/IDotD/wiki/Developer-Information#commits has the possible texts :)

**Pull request merged**
