### PR TITLE
Refactoring settings, moving all string to a single module and code climate update.

### PR DESCRIPTION
**Pull request by w20k**

### CODE REVIEW

**Comment by w20k** [comment]
Something wrong with codeclimate :)

**Comment by Idrinth** [comment]
1st: raids.js:155 - typo, did that even work?
2nd: your settings refactoring does not seem to adress old settings - yiu might want to check for them if the new ones aren't around.
3rd: is there a reason the settings starting moved into the general area?

**Comment by Idrinth** [comment]
regarding codeclimate, it is really similar lines :P but yes, the check is overly strict in those two cases

**Comment by w20k** [comment]
> 1st:raids.js:155 - typo, did that even work?

It was a typo. Still testing, was thinking to tackle testing tomorrow at work. Just wanted your opinion on refactoring process.

> 2nd: your settings refactoring does not seem to address old settings - you might want to check for them if the new ones aren't around.

You're right added a comment in the specified task. Will deal with that tomorrow ;)

**Comment by w20k** [comment]
> 3rd: is there a reason the settings starting moved into the general area?

I was thinking that settings should have only application options and all utility functions should move to "util" module. Probably, "stable.js" might not be a good place. You're right :)

**Comment by Idrinth** [comment]
besides the mentioned points it looks fine to me, would merge it once 1 and 2 are solved

**Comment by w20k** [comment]
Do you think making settings more transperent is a bad idea, moving utility functions to another module?

**Comment by Idrinth** [comment]
I don't think settings really needs to have fewer methods, it is already down to a small amount of them:
- load
- change(&save)
- save

I think the save one could work fine as a sub-method of change - as in write once it changed, but that's about it.

After having another look at your loading-function, it would even overwrite the defaults, since it just takes any result it has as the whole set of settings. Adding new ones would not be possible that way either. You might want to replace that with iteration over object keys.
Objects there currently only have two levels, but with the local raid filtering I'd assume we will get up to 3, so you might want to make it recursive.

**Comment by w20k** [comment]
I revised setting a bit. Will do tests run and have a proper lunch. Want to look through one more time.

**Comment by Idrinth** [comment]
if you don't mind, could you do the changes to the linter-configuration independant of the code changes(other branch)? Makes sure we can pull one but not the other if only one works

**Comment by w20k** [comment]
Sorry, I was just testing codeclimate. Was looking for an option to lower the duplicate madness.

**Comment by Idrinth** [comment]
I'll manually check those for the time being, don't worry about them :)

Tell me if it works with the old settings, looks functional at first glance ;)

**Comment by w20k** [comment]
Thanks a lot :D But don't merge yet. I will do some tests after 17:00 o'clock. Just to be sure everything is okey.

**Comment by w20k** [comment]
I'm a bit 'overcooked', so this PR will grow beard here for a while ;)

**Comment by Idrinth** [comment]
Will merge your branch into mine then and finish it.

**Comment by w20k** [comment]
@Idrinth got everything work related. I will deal with bugs today, if you don't mind, just want to finish myself :)

**Comment by Idrinth** [comment]
all right, was way lower on time myself lately, so didn't make much progress /

**Comment by w20k** [comment]
Could review my pull request.

**Comment by w20k** [comment]
Hm...don't merge yet :) Thanks!

**Comment by w20k** [comment]
Sorry, Haven't been in town for a while, just got back a week ago.

**Comment by Idrinth** [comment]
don't worry about it, I didn't hire you, so I got no right to your time :)

**Comment by Idrinth** [comment]
did you give up on the refactoring, @w20k ?

**Comment by w20k** [comment]
Nope, just need to sync with master, and your refactoring. And start from scratch have an idea ;) No, worries.
Weekends will be fun :)

**Comment by Idrinth** [comment]
did you get the invite to https://idotd.slack.com btw? used your commit-email, might be easier to talk there, so we don't abuse merge/pull-requests for that :D

**Comment by w20k** [comment]
Could you send it to my another email :) Which is used with codeclimate?Thanks !

**Comment by Idrinth** [comment]
No chance for me to get that email afaik, you could send me a quick mail to the webmaster email of my domain :)

**Pull request closed without merging**
