### PR TITLE
Idrinth

### LINKED ISSUE #27: Function 'process' has a complexity of 10. (complexity)
#### Occurred on:
+ **Commit**:  94410f57db8588a6828b3c5ae3b2bec9e426245f
+ **File**:    [mods/war.js](https://github.com/Idrinth/IDotD/blob/94410f57db8588a6828b3c5ae3b2bec9e426245f/mods/war.js)
+ **LineNum**: [40](https://github.com/Idrinth/IDotD/blob/94410f57db8588a6828b3c5ae3b2bec9e426245f/mods/war.js#L40)
+ **Code**:    `function process ( data ) {`

    
#### Currently on:
+ **Commit**:  c60ae9b03162cdbd7f553c4a8ce1c928243fba50
+ **File**:    [mods/war.js](https://github.com/Idrinth/IDotD/blob/c60ae9b03162cdbd7f553c4a8ce1c928243fba50/mods/war.js)
+ **LineNum**: [40](https://github.com/Idrinth/IDotD/blob/c60ae9b03162cdbd7f553c4a8ce1c928243fba50/mods/war.js#L40)

### PR DESCRIPTION
**Pull request by Idrinth**
@w20k could you please have a quick look at the war-module in here?
Should fix #27

### CODE REVIEW

**Comment by w20k** [comment]
Will take a look.

**Comment by w20k** [comment]
How should I proceed with changes? 
Should I commit into your branch or add a patch? What do you think?

**Comment by Idrinth** [comment]
Commit into your own branch, merge properly to the master and let me worry about my own :P we need to merge back once in a while anyway or we'll lose changes.

**Comment by Idrinth** [comment]
Weird, looks like my comment disapeared:
I would keep (at least) one private branch to later merge back into the master. Updating your own branch (es) is something you need to take care of yourself - or just start a fresh one every time you pick a task.

**Pull request merged**
